// AUTO-GENERATED by content_scaffold — do not edit.
declare module 'virtual:content' {
  export const home: { "hero": { "eyebrow": string; "title": string; "subtitle": string; "cta": string; "note": string }; "footer": { "copyright": string; "link": string } };
}
