// AUTO-GENERATED by content_scaffold — do not edit.
declare module 'virtual:content' {
  export const home: { "hero": { "eyebrow": string; "title": string; "description": string; "button": string; "response": string } };
}
